### ISSUE TITLE
Liquid Exception: undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by stewartknapman** [myles/jekyll-typogrify#1]
I have a liquid template that looks like this: 

    <div class="page">
      <header class="page-header">
        <h1>{{ page.title | improve }}</h1>
      </header>
  
      <div class="page-content">
        {{ content | improve }}
      </div>
    </div>

`{{ content | improve }}` is working as expected but `{{ page.title | improve }}` throws the Liquid Exception: undefined method `gsub' for nil:NilClass

It only seems to be the title property on the page object that is having an issue.
If I change `{{ page.title }}` to output without a filter or to use a core filter like `{{ page.title | split: ' ' }}` then every thing seems to work fine.
If I use a different property on the page object like `{{ page.name | improve }}` then this also works fine.

Using another object also works as expected without error:

    {% for page in site.pages %}
      {% if page.name == 'home.markdown' %}
        {% assign homepage = page  %}
      {% endif %}
    {% endfor %}
    {{ homepage.title | improve }}

Let me know if you need anymore details

**Comment by myles** [comment]
Do you mind sharing an example of the what is being passed to the `{{ page.title }}` so I can test.

**Comment by stewartknapman** [comment]
Yea, sure. It will have to be Monday morning though (nz time)

**Comment by stewartknapman** [comment]
This is the front matter for two pages where I am seeing the issue:

    ---
    title: About Us
    date: 2016-01-15 14:44:00 +13:00
    ---

    ---
    title: XLam Cross Laminated Timber Panels
    date: 2016-01-15 13:15:00 +13:00
    ---

**Comment by myles** [comment]
Have you enabled the plugin in your `_config.yml` file?

If not you will need to add the following:

```yaml
gems:
- jekyll-typogrify
```

**Comment by stewartknapman** [comment]
@myles I have added this to the config, however I am still seeing the same issue after reloading jekyll.

Here is a link to a video of what I am seeing: https://monosnap.com/file/3junoV3wH1W2bieWfn1t85yz3hLZmN

Hope this helps.

**Comment by myles** [comment]
Can you you posting the output of `jekyll -v`, `jekyll build --verbose`, and `jekyll build --trace` so I can get a better understand of the error.

**Comment by stewartknapman** [comment]
$ jekyll -v
    jekyll 3.0.1

    $ jekyll build --verbose
      Logging at level: debug
    Configuration file: /Users/stewartknapman/Development/Siteleaf/Xlam/_config.yml
         PluginManager: Requiring jekyll-typogrify
                Source: /Users/stewartknapman/Development/Siteleaf/Xlam
           Destination: /Users/stewartknapman/Development/Siteleaf/Xlam/_site
     Incremental build: disabled. Enable with --incremental
          Generating... 
           EntryFilter: excluded?(/default.html) ==> false
           EntryFilter: excluded?(/page.html) ==> false
           EntryFilter: excluded?(/wireframe.html) ==> false
           EntryFilter: excluded?(/about-us) ==> false
           EntryFilter: excluded?(/css) ==> false
           EntryFilter: excluded?(/feed.xml) ==> false
           EntryFilter: excluded?(/Gemfile) ==> false
           EntryFilter: excluded?(/Gemfile.lock) ==> false
           EntryFilter: excluded?(/home.markdown) ==> false
           EntryFilter: excluded?(/imgs) ==> false
           EntryFilter: excluded?(/index.html) ==> false
           EntryFilter: excluded?(/js) ==> true
           EntryFilter: excluded?(/node_modules) ==> true
           EntryFilter: excluded?(/package.json) ==> true
           EntryFilter: excluded?(/styleguide) ==> false
           EntryFilter: excluded?(/wireframes) ==> false
           EntryFilter: excluded?(/about-us/index.markdown) ==> false
           EntryFilter: excluded?(/about-us/partnering.markdown) ==> false
           EntryFilter: excluded?(/about-us/the-company.markdown) ==> false
           EntryFilter: excluded?(/about-us/the-xlam-team.markdown) ==> false
           EntryFilter: excluded?(/css/styleguide.css) ==> false
           EntryFilter: excluded?(/css/styles.css) ==> false
           EntryFilter: excluded?(/css/styles.min.css) ==> false
           EntryFilter: excluded?(/css/wireframes.css) ==> false
           EntryFilter: excluded?(/imgs/CaseStudy_image.jpg) ==> false
           EntryFilter: excluded?(/imgs/Hero_image.jpg) ==> false
           EntryFilter: excluded?(/imgs/Xlam-logo.svg) ==> false
           EntryFilter: excluded?(/styleguide/index.html) ==> false
           EntryFilter: excluded?(/wireframes/about.html) ==> false
           EntryFilter: excluded?(/wireframes/case-studies.html) ==> false
           EntryFilter: excluded?(/wireframes/case-study.html) ==> false
           EntryFilter: excluded?(/wireframes/contact.html) ==> false
           EntryFilter: excluded?(/wireframes/index.html) ==> false
           EntryFilter: excluded?(/wireframes/news.html) ==> false
           EntryFilter: excluded?(/wireframes/product.html) ==> false
           EntryFilter: excluded?(/wireframes/services.html) ==> false
           EntryFilter: excluded?(/wireframes/technical.html) ==> false
           EntryFilter: excluded?(_team/ian-jack.markdown) ==> false
           EntryFilter: excluded?(_team/rob-de-brincat.markdown) ==> false
           EntryFilter: excluded?(_team/robin-jack.markdown) ==> false
           EntryFilter: excluded?(_team/sam-leslie.markdown) ==> false
               Reading: _team/ian-jack.markdown
               Reading: _team/rob-de-brincat.markdown
               Reading: _team/robin-jack.markdown
               Reading: _team/sam-leslie.markdown
             Rendering: _team/robin-jack.markdown
             Rendering: _team/robin-jack.markdown
      Pre-Render Hooks: _team/robin-jack.markdown
      Rendering Liquid: _team/robin-jack.markdown
      Rendering Markup: _team/robin-jack.markdown
      Pre-Render Hooks: _team/robin-jack.markdown
      Rendering Liquid: _team/robin-jack.markdown
      Rendering Markup: _team/robin-jack.markdown
      Rendering Layout: _team/robin-jack.markdown
             Rendering: _team/ian-jack.markdown
             Rendering: _team/ian-jack.markdown
      Pre-Render Hooks: _team/ian-jack.markdown
      Rendering Liquid: _team/ian-jack.markdown
      Rendering Markup: _team/ian-jack.markdown
      Pre-Render Hooks: _team/ian-jack.markdown
      Rendering Liquid: _team/ian-jack.markdown
      Rendering Markup: _team/ian-jack.markdown
      Rendering Layout: _team/ian-jack.markdown
             Rendering: _team/rob-de-brincat.markdown
             Rendering: _team/rob-de-brincat.markdown
      Pre-Render Hooks: _team/rob-de-brincat.markdown
      Rendering Liquid: _team/rob-de-brincat.markdown
      Rendering Markup: _team/rob-de-brincat.markdown
      Pre-Render Hooks: _team/rob-de-brincat.markdown
      Rendering Liquid: _team/rob-de-brincat.markdown
      Rendering Markup: _team/rob-de-brincat.markdown
      Rendering Layout: _team/rob-de-brincat.markdown
             Rendering: _team/sam-leslie.markdown
             Rendering: _team/sam-leslie.markdown
      Pre-Render Hooks: _team/sam-leslie.markdown
      Rendering Liquid: _team/sam-leslie.markdown
      Rendering Markup: _team/sam-leslie.markdown
      Pre-Render Hooks: _team/sam-leslie.markdown
      Rendering Liquid: _team/sam-leslie.markdown
      Rendering Markup: _team/sam-leslie.markdown
      Rendering Layout: _team/sam-leslie.markdown
             Rendering: /wireframes/about.html
      Pre-Render Hooks: /wireframes/about.html
      Rendering Liquid: /wireframes/about.html
      Rendering Markup: /wireframes/about.html
      Rendering Layout: wireframes/about.html
     Post-Render Hooks: /wireframes/about.html
             Rendering: /wireframes/case-studies.html
      Pre-Render Hooks: /wireframes/case-studies.html
      Rendering Liquid: /wireframes/case-studies.html
      Rendering Markup: /wireframes/case-studies.html
      Rendering Layout: wireframes/case-studies.html
     Post-Render Hooks: /wireframes/case-studies.html
             Rendering: /wireframes/case-study.html
      Pre-Render Hooks: /wireframes/case-study.html
      Rendering Liquid: /wireframes/case-study.html
      Rendering Markup: /wireframes/case-study.html
      Rendering Layout: wireframes/case-study.html
     Post-Render Hooks: /wireframes/case-study.html
             Rendering: /wireframes/contact.html
      Pre-Render Hooks: /wireframes/contact.html
      Rendering Liquid: /wireframes/contact.html
      Rendering Markup: /wireframes/contact.html
      Rendering Layout: wireframes/contact.html
     Post-Render Hooks: /wireframes/contact.html
             Rendering: feed.xml
      Pre-Render Hooks: feed.xml
      Rendering Liquid: feed.xml
      Rendering Markup: feed.xml
      Rendering Layout: feed.xml
      Liquid Exception: undefined method `gsub' for nil:NilClass in _layouts/page.html
    jekyll 3.0.1 | Error:  undefined method `gsub' for nil:NilClass

    $ jekyll build --trace
    Configuration file: /Users/stewartknapman/Development/Siteleaf/Xlam/_config.yml
                Source: /Users/stewartknapman/Development/Siteleaf/Xlam
           Destination: /Users/stewartknapman/Development/Siteleaf/Xlam/_site
     Incremental build: disabled. Enable with --incremental
          Generating... 
      Liquid Exception: undefined method `gsub' for nil:NilClass in _layouts/page.html
    /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/typogruby-1.0.18/lib/typogruby.rb:287:in `exclude_sensitive_tags': undefined method `gsub' for nil:NilClass (NoMethodError)
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/typogruby-1.0.18/lib/typogruby.rb:62:in `amp'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/typogruby-1.0.18/lib/typogruby.rb:243:in `improve'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-typogrify-0.1.1/lib/jekyll/typogrify.rb:40:in `improve'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/strainer.rb:51:in `invoke'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/context.rb:95:in `invoke'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/variable.rb:88:in `block in render'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/variable.rb:86:in `each'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/variable.rb:86:in `inject'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/variable.rb:86:in `render'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/convertible.rb:112:in `render_liquid'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/convertible.rb:215:in `render_all_layouts'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/convertible.rb:263:in `do_layout'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/page.rb:116:in `render'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/site.rb:179:in `block in render'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/site.rb:177:in `each'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/site.rb:177:in `render'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/site.rb:59:in `process'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/command.rb:28:in `process_site'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:60:in `build'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:35:in `process'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/bin/jekyll:23:in `load'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/bin/jekyll:23:in `<main>'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
            from /Users/stewartknapman/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by stewartknapman** [comment]
Ahhhhhhh @myles I just worked it out!

I have a feed.xml file and it's trying to use this layout file when it shouldn't. Setting the layout in this file to be nothing fixes the issue.

Sorry to have wasted your time.

**Comment by myles** [comment]
@stewartknapman not a problem. Glad you are using my library and it's working for you.
