### ISSUE TITLE
Em dash detection doesn't work unless surrounded by spaces

### ISSUE THREAD

**Issue by SixFingeredAmish** [myles/jekyll-typogrify#11]
### Description:

Currently, the plugin only recognizes em dashes when they are surrounded by spaces, ie. "job — we"
Doesn't work when there are no spaces "job—we"

### Tell us a bit about yourself:
* Version of Jekyll::Typogrify I'm using <HINT: use `bundle show` to check>:
* Version of Jekyll I'm using <HINT: use `bundle show` to check>: 0.3.4
* Version of Ruby I'm using: 
* Operating System <e.g. Linux, OS X, Windows>: OS X High Sierra
* Browser <e.g, Safari, Chrome>: Chrome 68

**Comment by myles** [comment]
@SixFingeredAmish, I just added a test to check and it seems to work on both:

```
{{ "And yet, when the car was finally delivered—nearly three months after it was ordered—she decided she no longer wanted it, leaving the dealer with an oddly equipped car that would be difficult to sell." | jt_emdash }}


```

**Comment by myles** [comment]
@SixFingeredAmish fixed will deploy new version soon.
