### ISSUE TITLE
Issues with hyphenated words

### ISSUE THREAD

**Issue by SixFingeredAmish** [myles/jekyll-typogrify#6]
### Description:
When there is a word with hyphenation (ie. M65-A), caps will only apply to M65. I understand caps only triggers when there are multiple capital letters next to each other, but I think with hyphenation, it should wrap the whole thing.

### Tell us a bit about yourself:
* Version of Jekyll::Typogrify I'm using <HINT: use `bundle show` to check>: 0.3.2
* Version of Jekyll I'm using <HINT: use `bundle show` to check>: 3.4.3
* Version of Ruby I'm using: 2.5.0
* Operating System <e.g. Linux, OS X, Windows>: OS X High Sierra
* Browser <e.g, Safari, Chrome>: N/A

### Steps to reproduce:

For words with caps and hyphens, caps class does not wrap the whole word

### I expected the following:

Expected caps class to be applied to the whole word (M65-A)

### But got the following, instead:

Caps class wraps (M65)

**Comment by myles** [comment]
I've add this functionality as `jt_caps`, as it's not currently in the [Typogruby](http://avdgaag.github.io/typogruby/) library.

I will publish a new version of the library some time this month, after I do the proper testing.
